#pragma kernel CSMain

#include_with_pragmas "vertex.hlsl"

RWStructuredBuffer<Vertex> vertexBuffer;
RWStructuredBuffer<float3> velocityBuffer;
RWStructuredBuffer<float3> predictedPositionBuffer;

float2 _GridSize;
uint2 _GridCount;

float3 _Gravity;
float _Resistance;
float _DeltaTime;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _GridCount.x || id.y + 1 >= _GridCount.y)
        return;

    uint index = (id.y + 1) * _GridCount.x + id.x;

    float3 velocity = velocityBuffer[index];
    float3 position = vertexBuffer[index].position;
    
    velocity += _Gravity;
    velocity -= _Resistance * _DeltaTime * velocity;
    
    position += velocity * _DeltaTime;
    position.y = max(position.y, 0);

    velocityBuffer[index] = velocity;
    predictedPositionBuffer[index] = position;

    if (id.y == 0)
    {
        uint backIndex = id.x;
        predictedPositionBuffer[backIndex] = vertexBuffer[backIndex].position;
    }
}