#pragma kernel CSMain

RWStructuredBuffer<float3> predictedPositionBuffer;

float2 _GridSize;
uint2 _GridScale;
uint2 _GridCount;

float _GravityCoef;
float _DeltaTime;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint2 originalGridId = id.xy * _GridScale;

    if (originalGridId.x >= _GridCount.x || originalGridId.y >= _GridCount.y)
        return;

    uint index = originalGridId.y * _GridCount.x + originalGridId.x;

    float3 position = predictedPositionBuffer[index];
}