#pragma kernel CSMain

struct Vertex {
    float3 position;
    float2 uv;
    float3 normal;
};

RWStructuredBuffer<Vertex> vertexBuffer;
RWStructuredBuffer<float3> velocityBuffer;
RWStructuredBuffer<float3> predictedPositionBuffer;

float2 _GridSize;
uint2 _GridCount;

float _DeltaTime;

float3 ComputeVertexNormal(uint3 id, float3 vertexPosition)
{
    bool isLeftValid = id.x > 0;
    bool isRightValid = id.y < _GridCount.x - 1;
    // The backward vertex is always valid.
    bool isForwardValid = id.y + 1 < _GridCount.y - 1;

    float3 leftVertexDirection = float3(0, 0, 0);
    float3 rightVertexDirection = float3(0, 0, 0);
    float3 backwardVertexDirection = float3(0, 0, 0);
    float3 forwardVertexDirection = float3(0, 0, 0);

    if (isLeftValid)
    {
        uint leftIndex = (id.y + 1) * _GridCount.x + id.x - 1;
        float3 leftVertexPosition = vertexBuffer[leftIndex].position;
        leftVertexDirection = leftVertexPosition - vertexPosition;
    }
    if (isRightValid)
    {
        uint rightIndex = (id.y + 1) * _GridCount.x + id.x + 1;
        float3 rightVertexPosition = vertexBuffer[rightIndex].position;
        rightVertexDirection = rightVertexPosition - vertexPosition;
    }

    uint backwardIndex = id.y * _GridCount.x + id.x;
    float3 backwardVertexPosition = vertexBuffer[backwardIndex].position;
    backwardVertexDirection = backwardVertexPosition - vertexPosition;

    if (isForwardValid)
    {
        uint forwardIndex = (id.y + 2) * _GridCount.x + id.x;
        float3 forwardVertexPosition = vertexBuffer[forwardIndex].position;
        forwardVertexDirection = forwardVertexPosition - vertexPosition;
    }

    uint triangleCount = 0;
    float3 sumTriangleNormals = float3(0, 0, 0);

    if (isLeftValid)
    {
        sumTriangleNormals += normalize(cross(leftVertexDirection, backwardVertexDirection));
        triangleCount += 1;
    }
    if (isRightValid)
    {
        sumTriangleNormals += normalize(cross(rightVertexDirection, backwardVertexDirection));
        triangleCount += 1;
    }
    if (isLeftValid & isForwardValid)
    {
        sumTriangleNormals += normalize(cross(leftVertexDirection, forwardVertexDirection));
        triangleCount += 1;
    }
    if (isRightValid & isForwardValid)
    {
        sumTriangleNormals += normalize(cross(rightVertexDirection, forwardVertexDirection));
        triangleCount += 1;
    }

    return (triangleCount > 0) ? (sumTriangleNormals / triangleCount) : float3(0, 0, 0);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _GridCount.x || id.y + 1 >= _GridCount.y)
        return;

    uint index = (id.y + 1) * _GridCount.x + id.x;

    float3 delta = predictedPositionBuffer[index] - vertexBuffer[index].position;
    velocityBuffer[index] = delta / _DeltaTime;

    float3 vertexPosition = predictedPositionBuffer[index];
    vertexBuffer[index].position = vertexPosition;
    vertexBuffer[index].normal = ComputeVertexNormal(id, vertexPosition);
}