#pragma kernel CSMain

#include_with_pragmas "vertex.hlsl"
#include_with_pragmas "ApplyConstraints.hlsl"

RWStructuredBuffer<Vertex> vertexBuffer;

float2 _GridSize;
uint2 _GridCount;
bool _IsPageFlipped;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _GridCount.x || id.y >= _GridCount.y)
        return;

    uint index = id.y * _GridCount.x + id.x;
    int gridDir = _IsPageFlipped ? -1 : 1;

    float3 position = float3(
        id.x * _GridSize.x, 
        0, 
        gridDir * int(id.y) * _GridSize.y);

    position = ApplyConstraints(id, position);
    
    vertexBuffer[index].position = position;
    vertexBuffer[index].normal = float3(0, gridDir, 0);
}