#pragma kernel CSMain

#include_with_pragmas "vertex.hlsl"

RWStructuredBuffer<Vertex> vertexBuffer;
RWStructuredBuffer<float3> velocityBuffer;
RWStructuredBuffer<float3> predictedPositionBuffer;

float2 _GridSize;
uint2 _GridCount;

float _DeltaTime;

float3 ComputeVertexNormal(uint2 targetId, float3 vertexPosition)
{
    bool isLeftValid = targetId.x > 0;
    bool isRightValid = targetId.x < _GridCount.x - 1;
    bool isBackwardValid = targetId.y > 0;
    bool isForwardValid = targetId.y < _GridCount.y - 1;

    float3 leftVertexDirection = float3(0, 0, 0);
    float3 rightVertexDirection = float3(0, 0, 0);
    float3 backwardVertexDirection = float3(0, 0, 0);
    float3 forwardVertexDirection = float3(0, 0, 0);

    if (isLeftValid)
    {
        uint leftIndex = targetId.y * _GridCount.x + targetId.x - 1;
        float3 leftVertexPosition = vertexBuffer[leftIndex].position;
        leftVertexDirection = leftVertexPosition - vertexPosition;
    }
    if (isRightValid)
    {
        uint rightIndex = targetId.y * _GridCount.x + targetId.x + 1;
        float3 rightVertexPosition = vertexBuffer[rightIndex].position;
        rightVertexDirection = rightVertexPosition - vertexPosition;
    }
    if (isBackwardValid)
    {
        uint backwardIndex = (targetId.y - 1) * _GridCount.x + targetId.x;
        float3 backwardVertexPosition = vertexBuffer[backwardIndex].position;
        backwardVertexDirection = backwardVertexPosition - vertexPosition;    
    }
    if (isForwardValid)
    {
        uint forwardIndex = (targetId.y + 1) * _GridCount.x + targetId.x;
        float3 forwardVertexPosition = vertexBuffer[forwardIndex].position;
        forwardVertexDirection = forwardVertexPosition - vertexPosition;
    }

    uint triangleCount = 0;
    float3 sumTriangleNormals = float3(0, 0, 0);

    if (isLeftValid & isBackwardValid)
    {
        sumTriangleNormals += normalize(cross(backwardVertexDirection, leftVertexDirection));
        triangleCount += 1;
    }
    if (isRightValid & isBackwardValid)
    {
        sumTriangleNormals += normalize(cross(rightVertexDirection, backwardVertexDirection));
        triangleCount += 1;
    }
    if (isLeftValid & isForwardValid)
    {
        sumTriangleNormals += normalize(cross(leftVertexDirection, forwardVertexDirection));
        triangleCount += 1;
    }
    if (isRightValid & isForwardValid)
    {
        sumTriangleNormals += normalize(cross(forwardVertexDirection, rightVertexDirection));
        triangleCount += 1;
    }

    return (triangleCount > 0) ? (sumTriangleNormals / triangleCount) : float3(0, 0, 0);
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _GridCount.x || id.y + 1 >= _GridCount.y)
        return;

    uint index = (id.y + 1) * _GridCount.x + id.x;

    float3 delta = predictedPositionBuffer[index] - vertexBuffer[index].position;
    velocityBuffer[index] = delta / _DeltaTime;

    float3 vertexPosition = predictedPositionBuffer[index];
    vertexBuffer[index].position = vertexPosition;
    vertexBuffer[index].normal = ComputeVertexNormal(uint2(id.x, id.y + 1), vertexPosition);

    if (id.y == 0)
    {
        index = id.x;
        vertexPosition = vertexBuffer[index].position;
        vertexBuffer[index].normal = ComputeVertexNormal(uint2(id.x, id.y), vertexPosition);
    }
}